# Generated by Django 5.2.8 on 2025-11-28 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("client", "Client"),
                            ("freelancer", "Freelancer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(max_length=65535)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "faq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=65535)),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        help_text="Store attachment URLs/paths as JSON array",
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum budget",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum budget",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="admin_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
            options={
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="client_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("wilaya", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="freelancer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                ("categories", models.JSONField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("wilaya", models.CharField(blank=True, max_length=120, null=True)),
                ("years_experience", models.IntegerField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                ("social_links", models.JSONField(blank=True, null=True)),
                (
                    "rate",
                    models.FloatField(
                        blank=True,
                        help_text="Rating on 5 stars scale (decimal [0, 2])",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("education", models.JSONField(blank=True, null=True)),
                ("ccp_account", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "barid_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cvatta", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "freelancers",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=120, unique=True)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "representative",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="Company_logos/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Negotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_type",
                    models.CharField(
                        choices=[
                            ("direct_hire", "Direct Hire"),
                            ("request", "Request"),
                            ("job_offer", "Job Offer"),
                        ],
                        help_text="How the negotiation was initiated",
                        max_length=20,
                    ),
                ),
                (
                    "client_description",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                ("client_attachments", models.JSONField(blank=True, null=True)),
                ("client_agreed", models.BooleanField(default=False)),
                ("freelancer_attachments", models.JSONField(blank=True, null=True)),
                ("freelancer_agreed", models.BooleanField(default=False)),
                (
                    "decline_reason",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("agreed", "Agreed"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiations_declined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related request if origin_type is 'request'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="platform_api.request",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_client",
                        to="platform_api.client",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_freelancer",
                        to="platform_api.freelancer",
                    ),
                ),
            ],
            options={
                "db_table": "negotiations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "negotiation",
                    models.OneToOneField(
                        help_text="The negotiation that created this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="platform_api.negotiation",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, help_text="Estimated duration in days", null=True
                    ),
                ),
                (
                    "deliverables",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("waiting_client_review", "Waiting For Client Review"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="platform_api.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_phases",
                "ordering": ["project", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "textcontent",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_items",
                        to="platform_api.projectphase",
                    ),
                ),
            ],
            options={
                "db_table": "deliverables",
                "ordering": ["phase", "submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("client", "Client Report"),
                            ("post", "Post Report"),
                            ("comment", "Comment Report"),
                            ("freelancer", "Freelancer Report"),
                            ("request", "Request Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(help_text="ID of the reported entity"),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Description of the report", max_length=65535
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="request",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="platform_api.client",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, max_length=65535, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="platform_api.client",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="platform_api.freelancer",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Help",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        help_text="Description of the problem", max_length=65535
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Ticket",
                "verbose_name_plural": "Help Tickets",
                "db_table": "help",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="help_status_193c8f_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="help_user_id_645980_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobInternshipOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("job", "Job"), ("internship", "Internship")],
                        max_length=20,
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        help_text="Job requirements and qualifications",
                        max_length=65535,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '3 months', '1 year', 'Permanent'",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "what_we_offer",
                    models.TextField(
                        blank=True,
                        help_text="Benefits and what the company offers",
                        max_length=65535,
                        null=True,
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="company_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_offers",
                        to="platform_api.company",
                    ),
                ),
            ],
            options={
                "db_table": "job_internship_offers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "type", "created_at"],
                        name="job_interns_company_f7b116_idx",
                    ),
                    models.Index(
                        fields=["type", "created_at"],
                        name="job_interns_type_4cd91f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("freelancer_cv", "Freelancer CV"),
                            ("company_document", "Company Document"),
                            ("job_attachment", "Job Attachment"),
                            ("request_attachment", "Request Attachment"),
                            ("negotiation_attachment", "Negotiation Attachment"),
                            ("phase_deliverable", "Phase Deliverable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.IntegerField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file_url",
                    models.TextField(
                        help_text="URL or path to the file", max_length=65535
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="MIME type or file extension", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="media_files_entity__ef5d6e_idx",
                    ),
                    models.Index(
                        fields=["owner", "created_at"],
                        name="media_files_owner_i_325412_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NegotiationFloatingComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=65535)),
                (
                    "x_position",
                    models.FloatField(
                        blank=True,
                        help_text="X coordinate for floating comment",
                        null=True,
                    ),
                ),
                (
                    "y_position",
                    models.FloatField(
                        blank=True,
                        help_text="Y coordinate for floating comment",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending ", "Pending"), ("resolved", "Resolved")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floating_comments",
                        to="platform_api.negotiation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="For threaded/nested comments",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="platform_api.negotiationfloatingcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiation_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "negotiation_floating_comments",
                "ordering": ["negotiation_id", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["negotiation", "created_at"],
                        name="negotiation_negotia_87620d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="negotiation_user_id_f1d095_idx",
                    ),
                    models.Index(
                        fields=["parent"], name="negotiation_parent__c7c4ab_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NegotiationPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "deliverables",
                    models.TextField(blank=True, max_length=65535, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                            ("revision_required", "Revision Required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="platform_api.negotiation",
                    ),
                ),
            ],
            options={
                "db_table": "negotiation_phases",
                "ordering": ["negotiation", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["negotiation", "status"],
                        name="negotiation_negotia_ae6e87_idx",
                    ),
                    models.Index(
                        fields=["deadline"], name="negotiation_deadlin_76332f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=65535)),
                ("seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["receiver", "seen", "created_at"],
                        name="notificatio_receive_92ed66_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["negotiation"], name="projects_negotia_21aa23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date", "end_date"], name="projects_start_d_cb24a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectphase",
            index=models.Index(
                fields=["project", "status"], name="project_pha_project_1b34f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectphase",
            index=models.Index(
                fields=["status", "created_at"], name="project_pha_status_277cea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["phase", "submitted_at"], name="deliverable_phase_i_9a031b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["type", "created_at"], name="reports_type_dbf816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reporter", "created_at"], name="reports_reporte_07de2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["client", "status", "created_at"],
                name="requests_client__e526ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["status", "created_at"], name="requests_status_e58b13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["category", "created_at"], name="requests_categor_de7393_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("client", "freelancer")},
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["client", "status", "created_at"],
                name="negotiation_client__db1382_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["freelancer", "status", "created_at"],
                name="negotiation_freelan_febb68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["status", "created_at"], name="negotiation_status_fc39a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["origin_type", "created_at"],
                name="negotiation_origin__32d77b_idx",
            ),
        ),
    ]
