# Generated by Django 5.2.8 on 2025-11-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negotiationfloatingcomment",
            name="x_position",
        ),
        migrations.RemoveField(
            model_name="negotiationfloatingcomment",
            name="y_position",
        ),
    ]
