# Generated by Django 5.2.8 on 2025-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0002_remove_negotiationfloatingcomment_x_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("freelancer", "Freelancer"),
                    ("company", "Company"),
                ],
                max_length=20,
            ),
        ),
    ]
