# Generated by Django 5.2.8 on 2025-12-09 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0003_alter_user_email_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="help",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("resolved", "Resolved")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(max_length=65535)),
                ("attachments", models.JSONField(blank=True, default=list, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="platform_api.communitypost",
                    ),
                ),
            ],
            options={
                "db_table": "community_likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(max_length=65535)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="For nested/threaded replies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="platform_api.communitycomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="platform_api.communitypost",
                    ),
                ),
            ],
            options={
                "db_table": "community_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["owner", "created_at"], name="community_p_owner_i_e72cc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["-created_at"], name="community_p_created_5c996b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitylike",
            index=models.Index(
                fields=["post", "created_at"], name="community_l_post_id_d17611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitylike",
            index=models.Index(
                fields=["user", "created_at"], name="community_l_user_id_128154_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitylike",
            unique_together={("post", "user")},
        ),
        migrations.AddIndex(
            model_name="communitycomment",
            index=models.Index(
                fields=["post", "created_at"], name="community_c_post_id_2fbac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitycomment",
            index=models.Index(
                fields=["user", "created_at"], name="community_c_user_id_494cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitycomment",
            index=models.Index(
                fields=["parent", "created_at"], name="community_c_parent__af87b4_idx"
            ),
        ),
    ]
