# Generated by Django 5.2.8 on 2025-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0004_alter_help_status_communitypost_communitylike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="title",
            field=models.CharField(blank=True, default="Deliverable", max_length=255),
        ),
    ]
