# Generated by Django 5.2.8 on 2026-01-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0005_deliverable_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('agreed', 'Agreed'), ('completed', 'Completed'), ('declined', 'Declined')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='negotiationfloatingcomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
