# Generated by Django 5.2.8 on 2026-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0006_alter_help_status_alter_negotiation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
