# Generated by Django 5.2.8 on 2026-01-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0007_predefinedrequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="predefinedrequest",
            new_name="predefined__categor_63f969_idx",
            old_name="predefined__category_is_ac_idx",
        ),
        migrations.RenameIndex(
            model_name="predefinedrequest",
            new_name="predefined__is_acti_b44c98_idx",
            old_name="predefined__is_acti_idx",
        ),
    ]
