export interface CategoryWithSkills {
  category: string;
  skills: string[];
}

export const categoriesWithSkills: CategoryWithSkills[] = [
  {
    category: "Development & IT",
    skills: [
      "Yeoman Developer",
      "UI Developer",
      "Twitter Developer",
      "Research Programmer",
      "Schema Developers",
      "Remote Developers",
      "Java Engineer",
      "Chrome OS Developer",
      "Blockchain Tester",
      "Amazon Backend Developer",
      "Ada Programmer",
      "Innovation Consultants",
      "GPT Neo Specialists",
      "Indian Web Developers",
      "Web Developers",
      "Big Data Engineers",
      "2D Game Developers",
      "Software Developers",
      "Google API Developers",
      "Microsoft Developers",
    ],
  },

  {
    category: "Design & Creative",
    skills: [
      "2D Game Assets Designers",
      "2D Game Designers",
      "Handmade Jewelry Designers",
      "Costume Designers",
      "Floral Designers",
      "Action Writers",
      "Marketing Designers",
      "Graphic Designers",
      "Evaluation Designers",
      "Adobe Photoshop Experts",
      "Youtube Video Editors",
      "Video Editors",
      "Final Cut Pro X Specialists",
      "Sound Engineers",
      "Logo Designers",
      "Mixing Engineers",
      "2D Animation Background Artists",
      "2D Illustrators",
      "Music Managers",
      "Adobe Illustrator Experts",
    ],
  },

  {
    category: "AI Services",
    skills: [
      "OpenAI Developers",
      "Artificial Intelligence Engineers",
      "AI Agent Developers",
      "Machine Learning Engineers",
      "Data Scientists",
      "OpenAI on AWS Developers",
      "Deep Learning Experts",
      "Pandas Developers",
      "Computer Vision Engineers",
      "NLP Engineers",
      "TensorFlow Developers",
      "PyTorch Freelancers",
      "Scikit-Learn Specialists",
      "OpenCV Developers",
      "Algorithm Developers",
      "Keras Freelancers",
      "Jupyter Specialists",
      "Deep Neural Networks Developers",
      "Predictive Analytics Specialists",
      "Artificial Neural Networks Experts",
    ],
  },

  {
    category: "Sales & Marketing",
    skills: [
      "Sales Analysts",
      "Marketing Analytics Consultants",
      "Brand Marketing Consultants",
      "Social Media Experts",
      "Social Media Specialists",
      "SEM Specialists",
      "Marketing Consultants",
      "SEO Managers",
      "Small Business Marketing Consultants",
      "Marketing Strategy Consultants",
      "Law Firm Marketing Consultants",
      "Digital Marketing Strategy Consultants",
      "Dental Marketing Consultants",
      "Business Marketing Consultants",
      "Healthcare Marketing Consultants",
      "Google Marketing Consultants",
      "Vertical Marketers",
      "Digital Marketers",
      "Lead Generation Experts",
      "Demand Generation Marketers",
    ],
  },

  {
    category: "Writing & Translation",
    skills: [
      "Book Reviewers",
      "Writers",
      "Manuscripts Specialists",
      "Newsletter Specialists",
      "Journal Writers",
      "CV Writers",
      "Content Writers",
      "Professional Writers",
      "Business Plan Writers",
      "Translators",
      "Document Translation Specialists",
      "Book Translators",
      "Article Translators",
      "Copywriters",
      "Dissertation Writers",
      "Science Fiction Writers",
      "Food Writers",
      "Proofreaders",
      "Grammar Freelancers",
      "Anime Writers",
    ],
  },

  {
    category: "Admin & Customer Support",
    skills: [
      "Systems Programmer",
      "Ebay Virtual Assistant",
      "Amazon Virtual Assistant",
      "Data Encoding Specialists",
      "CRM Data Entry Virtual Assistants",
      "CRM Data Entry Assistants",
      "Data Entry Specialists",
      "Data Entry Operators",
      "Virtual Assistants",
      "Medical Mastermind Medical Billers Services",
      "Google Calendar Developers",
      "Assistant Editors",
      "Auction Software Specialists",
      "Real Estate Virtual Assistants",
      "Customer Service Representatives",
      "Excel Experts",
      "Personal Assistants",
      "Project Managers",
      "Business Project Managers",
      "Certified Microsoft 365 Messaging Administrators",
    ],
  },

  {
    category: "Finance & Accounting",
    skills: [
      "Accounting Software Consultants",
      "Investment Managers",
      "Hedge Fund Managers",
      "Accounting Consultants",
      "IT Consultants",
      "Bookkeepers",
      "Financial Consultants",
      "Accounting Tutors",
      "Tax Consultants",
      "Education Consultants",
      "Management Consultants",
      "Communication skills Freelancers",
      "Bank Reconciliation Specialists",
      "Business Analysts",
      "Financial Analysts",
      "Business Development Representatives",
      "QuickBooks Consultants",
      "Xero Specialists",
      "Account Reconciliation Specialists",
      "Payroll Specialists",
    ],
  },

  {
    category: "Legal",
    skills: [
      "Contract Drafters",
      "IT Compliance Specialists",
      "Compliance Specialists",
      "Contract Law Lawyers & Legal Professionals",
      "Paralegals",
      "Legal Researchers",
      "Legal Assistants",
      "Legal Consultants",
      "Document Reviewers",
      "Corporate Law Lawyers & Legal Professionals",
      "Business Law Freelancers",
      "Securities Finance Lawyers",
      "Regulatory Compliance Freelancers",
      "Immigration Law Lawyers & Legal Professionals",
      "Copyright Lawyers",
      "Intellectual Property Law Lawyers & Legal Professionals",
      "Civil Law Lawyers & Legal Professionals",
      "Employment Law Lawyers & Legal Professionals",
      "Litigation Specialists",
      "Criminal Law Lawyers & Legal Professionals",
    ],
  },

  {
    category: "HR & Training",
    skills: [
      "Hiring Managers",
      "Recruiters",
      "Technology Freelancers",
      "Talent Management Professionals",
      "Human Resource Managers",
      "Training & Development Professionals",
      "LinkedIn Recruiters",
      "Instructional Designers",
      "Interviewers",
      "e-Learning Specialists",
      "Leadership Development Specialists",
      "Onboarding Specialists",
      "Candidate sourcing Freelancers",
      "Curriculum Developers",
      "Technical Recruiters",
      "Learning Management System (LMS) Specialists",
      "Organizational Development Consultants",
      "Employee Engagement Specialists",
      "Curriculum design Freelancers",
      "HR Consultants",
    ],
  },

  {
    category: "Engineering & Architecture",
    skills: [
      "Architectural Illustrator",
      "Design Engineers",
      "AutoCAD Experts",
      "Arduino Experts",
      "MATLAB Experts",
      "Professional Engineers",
      "Electrical Consulting Engineers",
      "Arduino Engineers",
      "Hardware Engineers",
      "Lighting Engineers",
      "Aerospace Engineers",
      "Agricultural Engineers",
      "Geotechnical Engineers",
      "3D Artists",
      "Engineering Consultants",
      "Product Designers",
      "AutoCAD Consultants",
      "Safety Consultants",
      "3D Modelers",
      "CAD Designers",
    ],
  },
];